// Bake the wonder → culture-prereq map from the OW reference XML so the stats
// layer can tell "nobody built it" from "nobody could build it".
//
// A wonder in Old World is an improvement flagged <bWonder>, and its only
// build gate is <CulturePrereq>: a city has to have reached that culture level
// before the wonder can be started there. Wonders carry no TechPrereq — verified
// across all 28 base-game entries — so culture level is the whole eligibility
// story, and the seven wonders at each of the four levels form natural tiers.
//
// SOURCES (local-only, via the Reference/ resolver — set OLD_WORLD_REFERENCE_DIR
// to an OW install or an XML checkout such as the owtournamentatlas repo):
//   Reference/XML/Infos/improvement.xml — <Entry> with <zType>, <bWonder>,
//                                          <CulturePrereq>
//   Reference/XML/Infos/culture.xml     — <Entry> with <zType>, in ascending
//                                          level order (WEAK → LEGENDARY)
//
// OUTPUT: src/lib/generated/wonders.ts (frontend) and cloud/src/generated/
// wonders.ts (Worker) — same module, both generated, no hand-mirroring (the
// law-classes pattern, minus the sidecar). law-classes routes through
// .bake/law-classes.json so bake:finalize emits it alongside the manifests it
// has to reconcile against the atlases; this bake has no asset output, so it
// writes its two modules directly rather than adding a hop that buys nothing.
// Nothing is at risk either way — finalize's reconciliation only unlinks under
// static/atlases/, static/sprites/, and assets/atlas-sources/, never a
// generated module (build-manifests.ts).
//
// Deterministic — re-running with the same XML is byte-identical.
//
// Run: npm run bake:wonders

import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUTS = [
	resolve(REPO_ROOT, "src/lib/generated/wonders.ts"),
	resolve(REPO_ROOT, "cloud/src/generated/wonders.ts"),
];

interface ImprovementEntry {
	zType?: string;
	bWonder?: string | number;
	CulturePrereq?: string;
}

interface CultureEntry {
	zType?: string;
}

const parser = new XMLParser({
	ignoreAttributes: true,
	parseTagValue: false,
	ignoreDeclaration: true,
	ignorePiTags: true,
});

async function loadEntries<T>(path: string): Promise<T[]> {
	const xml = await readFile(path, "utf-8");
	const parsed = parser.parse(xml) as { Root?: { Entry?: T | T[] } };
	const entry = parsed.Root?.Entry;
	if (entry == null) return [];
	return Array.isArray(entry) ? entry : [entry];
}

async function main(): Promise<void> {
	const infos = resolve(resolveReferenceXml(), "Infos");

	// culture.xml lists the levels in ascending order; that order IS the
	// ranking, so "does this city clear the prereq" is an index comparison.
	const levels = (
		await loadEntries<CultureEntry>(resolve(infos, "culture.xml"))
	)
		.map((c) => c.zType)
		.filter((z): z is string => !!z && z.startsWith("CULTURE_"));
	if (levels.length === 0) {
		throw new Error("bake-wonders: culture.xml yielded no CULTURE_* levels");
	}

	const improvements = await loadEntries<ImprovementEntry>(
		resolve(infos, "improvement.xml"),
	);
	const wonders: Record<string, string> = {};
	for (const i of improvements) {
		if (!i.zType || String(i.bWonder) !== "1") continue;
		const prereq = i.CulturePrereq;
		if (!prereq) {
			// Every base-game wonder has one; a mod entry without it would be
			// buildable from the start, which the eligibility math can't express.
			throw new Error(`bake-wonders: ${i.zType} has no CulturePrereq`);
		}
		if (!levels.includes(prereq)) {
			throw new Error(
				`bake-wonders: ${i.zType} wants unknown culture level ${prereq}`,
			);
		}
		wonders[i.zType] = prereq;
	}
	if (Object.keys(wonders).length === 0) {
		throw new Error(
			"bake-wonders: improvement.xml yielded no <bWonder> entries",
		);
	}

	const body = Object.keys(wonders)
		.sort()
		.map((k) => `\t${JSON.stringify(k)}: ${JSON.stringify(wonders[k])},`)
		.join("\n");

	const out =
		`// AUTO-GENERATED by scripts/bake-wonders.ts from Reference/XML/Infos\n` +
		`// (improvement.xml, culture.xml). Do not edit by hand — re-run\n` +
		`// \`npm run bake:wonders\`. Emitted identically to src/lib/generated/\n` +
		`// and cloud/src/generated/ (frontend + Worker).\n` +
		`//\n` +
		`// Culture levels in ascending order — a city clears a wonder's prereq\n` +
		`// when its own level's index is >= the prereq's.\n` +
		`export const CULTURE_LEVELS: readonly string[] = ${JSON.stringify(levels)};\n\n` +
		`// Wonder (an improvement flagged <bWonder>) → the culture level a city\n` +
		`// must have reached to build it. Wonders have no tech prereq, so this is\n` +
		`// the whole gate.\n` +
		`export const WONDER_CULTURE_PREREQ: Readonly<Record<string, string>> = {\n` +
		`${body}\n};\n\n` +
		`// Rank of a culture level (-1 when unknown), for prereq comparisons.\n` +
		`export function cultureRank(level: string | null): number {\n` +
		`\treturn level == null ? -1 : CULTURE_LEVELS.indexOf(level);\n` +
		`}\n`;

	for (const path of OUTPUTS) {
		await writeFile(path, out, "utf-8");
	}
	console.log(
		`[wonders] wrote ${Object.keys(wonders).length} wonders across ${levels.length} culture levels → ${OUTPUTS.length} modules`,
	);
}

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
