// Bake the community atlas' published map pool (src/lib/generated/atlas-pool.ts
// and cloud/src/generated/atlas-pool.ts) from a local owtournamentatlas
// checkout:
//
//   npx tsx scripts/bake-atlas-pool.ts
//
// OUTPUT: the same module to both paths, byte-identical — the arrangement
// bake-wonders, bake-law-classes and bake-nation-names already use, and the
// reason every file in cloud/src/generated/ has a same-named twin under
// src/lib/generated/. Both packages read the same eighteen rows and neither
// owns them: cloud/ is a separate package that can't import from src/lib, so
// the alternative to one baked module is two, which is how this started —
// an anchor→minSites table for the frontend beside an anchor→script/name
// table for the Worker, same rows, two names, two shapes, free to drift.
//
// Each package reads the fields it needs and indexes the array its own way:
//   * the frontend asks whether a map is in the atlas at all (its anchor
//     resolves to a real section, so it can be linked) and what its city-site
//     caveat is, for the admin scheduling DM — mapInAtlas and mapCaveatNote in
//     $lib/tournament/map-script-options;
//   * the Worker suggests a map to a pair of players whose script neither has
//     played lately — ratings/pick-map.ts, which needs `script` to compare
//     against their history and `name`/`setting` to say which map it means.
//
// Only the published pool: those are the duel-tuned configs the community
// actually plays, and the only ones whose anchors resolve on the atlas site, so
// every suggestion can be linked. Reading it — parsing POOL out of the atlas'
// index.astro, joining to atlas-dist.json, computing each anchor, resolving
// each script — lives in scripts/lib/atlas-pool.
//
// Deterministic: re-running against the same checkout is byte-identical.

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readAtlasPool } from "./lib/atlas-pool";

// Base URL of the community map atlas. Defined here rather than imported from
// $lib, because $lib/tournament/map-script-options reads the module this script
// emits — importing it back would make the baker unable to run whenever its
// own output is missing. Both packages read the baked copy; a fork repointing
// the atlas changes it here and re-bakes.
const ATLAS_BASE_URL = "https://alcaras.github.io/owtournamentatlas/";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUTS = [
	resolve(REPO_ROOT, "src/lib/generated/atlas-pool.ts"),
	resolve(REPO_ROOT, "cloud/src/generated/atlas-pool.ts"),
];

async function main(): Promise<void> {
	const pool = readAtlasPool();

	const rows = pool
		.map(
			(m) =>
				`\t{\n` +
				`\t\tanchor: ${JSON.stringify(m.anchor)},\n` +
				`\t\tscript: ${JSON.stringify(m.script)},\n` +
				`\t\tname: ${JSON.stringify(m.name)},\n` +
				`\t\tsetting: ${JSON.stringify(m.setting)},\n` +
				`\t\tminSites: ${m.minSites},\n` +
				`\t},`,
		)
		.join("\n");

	const out =
		`// Generated by scripts/bake-atlas-pool.ts — do not edit by hand.\n` +
		`// Source: owtournamentatlas' published pool (src/pages/index.astro POOL,\n` +
		`// joined to src/data/atlas-dist.json). Re-run when the atlas pool or its\n` +
		`// generation stats change.\n` +
		`//\n` +
		`// Emitted identically to src/lib/generated/ and cloud/src/generated/ —\n` +
		`// both packages read these rows and neither owns them.\n\n` +
		`// One map the community plays: what to call it, the script it runs, how\n` +
		`// it is set up, how few city sites it has been seen to spawn with, and\n` +
		`// the anchor that addresses it on the atlas.\n` +
		`//\n` +
		`// \`name\` carries the variant where the pool holds several of one script\n` +
		`// ("DOTA Jungle"); where two share a variant, \`setting\` is what tells\n` +
		`// them apart. \`script\` is the zType Old World declares — the same string\n` +
		`// games.map_class and tournament_matches.map_script carry, so it compares\n` +
		`// directly against a player's history. \`anchor\` is this map's identity:\n` +
		`// what a stored suggestion keeps, and what atlasAnchor() reproduces at\n` +
		`// runtime from a map_pool entry.\n` +
		`export interface AtlasPoolMap {\n` +
		`\tanchor: string;\n` +
		`\tscript: string;\n` +
		`\tname: string;\n` +
		`\tsetting: string;\n` +
		`\tminSites: number;\n` +
		`}\n\n` +
		`export const ATLAS_POOL: readonly AtlasPoolMap[] = [\n${rows}\n];\n\n` +
		`// Where the atlas lives; a map's link is this plus "#" plus its anchor.\n` +
		`// The one copy in the repo — the Worker reads it from here, and so does\n` +
		`// the frontend, which re-exports it from map-script-options.ts.\n` +
		`export const ATLAS_BASE_URL = ${JSON.stringify(ATLAS_BASE_URL)};\n`;

	for (const out_path of OUTPUTS) {
		writeFileSync(out_path, out);
		console.log(`wrote ${out_path} (${pool.length} maps)`);
	}
}

main().catch((err: unknown) => {
	console.error(err instanceof Error ? err.message : err);
	process.exit(1);
});
