// Bake every cognomen from the OW reference XML — the names the game
// gives its rulers, each with the legitimacy it is worth ("the Founder" at
// 10 … "the Great" at 100) and the string the game displays for it.
//
// This is the only bake that reads cognomen.xml. Two surfaces share the
// table: the players board names its activity rungs from it, and the
// Orders tab prices each ruler's cognomen into dynasty legitimacy — which
// is why the insults (the Bloody at −100) are here too, and why the table
// is keyed rather than filtered down to a ladder of honours.
//
// SOURCES (local-only, via the Reference/ symlink resolved by paths.ts):
//   Reference/XML/Infos/cognomen.xml — <iLegitimacy> per cognomen.
//   Reference/XML/Infos/text*.xml — TEXT_COGNOMEN_* display strings
//     (the DLC cognomens live in per-DLC text files, e.g. text-eoti.xml).
//
// OUTPUT: src/lib/generated/cognomens.ts (checked in, self-contained).
//
// Run: npm run bake:cognomens

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";
import { format as prettierFormat, resolveConfig } from "prettier";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_TS = resolve(REPO_ROOT, "src/lib/generated/cognomens.ts");

interface Entry {
	zType?: string;
	iLegitimacy?: string;
	"en-US"?: string;
}

const parser = new XMLParser({
	ignoreAttributes: true,
	parseTagValue: false,
	ignoreDeclaration: true,
	ignorePiTags: true,
});

async function loadEntries(path: string): Promise<Entry[]> {
	const xml = await readFile(path, "utf-8");
	const parsed = parser.parse(xml) as { Root?: { Entry?: Entry | Entry[] } };
	const raw = parsed.Root?.Entry;
	return raw == null ? [] : Array.isArray(raw) ? raw : [raw];
}

async function main(): Promise<void> {
	const infosDir = resolve(resolveReferenceXml(), "Infos");
	const textFiles = (await readdir(infosDir)).filter((f) =>
		/^text.*\.xml$/.test(f),
	);
	const [cognomens, ...textSets] = await Promise.all([
		loadEntries(resolve(infosDir, "cognomen.xml")),
		...textFiles.map((f) => loadEntries(resolve(infosDir, f))),
	]);
	const texts = textSets.flat();
	const textByType = new Map(texts.map((t) => [t.zType, t["en-US"]]));

	// The file's blank template Entry has no zType; everything else is a
	// real cognomen. COGNOMEN_NEW — what the game calls a fresh ruler —
	// carries no iLegitimacy because it is the starting state rather than an
	// award, so it prices at 0.
	const all = cognomens
		.filter((c) => c.zType)
		.map((c) => {
			// COGNOMEN_GREAT → TEXT_COGNOMEN_GREAT → "the Great". The gendered
			// variants are identical strings in English, so the base form is
			// the display name.
			const name = textByType.get(
				c.zType!.replace(/^COGNOMEN_/, "TEXT_COGNOMEN_"),
			);
			return {
				type: c.zType!,
				legitimacy: c.iLegitimacy != null ? Number(c.iLegitimacy) : 0,
				name: name ?? null,
			};
		});
	// Every cognomen must have display text — a missing string is a parse
	// drift, not an optional field.
	const missing = all.filter((c) => c.name == null);
	if (missing.length > 0) {
		throw new Error(
			`bake-cognomens: no display text for ${missing.map((c) => c.type).join(", ")}`,
		);
	}
	if (all.length < 60) {
		throw new Error(`bake-cognomens: only ${all.length} cognomens parsed`);
	}
	// Consumers index by zType, but the file is written in ascending
	// legitimacy — insults first, the Great last — so reading it shows the
	// ladder the game awards rather than an alphabetical list.
	all.sort(
		(a, b) => a.legitimacy - b.legitimacy || a.type.localeCompare(b.type),
	);
	const table: Record<string, { legitimacy: number; name: string }> = {};
	for (const c of all) {
		table[c.type] = { legitimacy: c.legitimacy, name: c.name! };
	}

	const lines: string[] = [];
	lines.push("// AUTO-GENERATED by scripts/bake-cognomens.ts. Do not edit.");
	lines.push("// Run `npm run bake:cognomens` to refresh from Reference/XML.");
	lines.push("");
	lines.push("export interface CognomenInfo {");
	lines.push("\t/** cognomen.xml iLegitimacy: negative for the insults, 0");
	lines.push("\t * for the New, which a fresh ruler starts with rather than");
	lines.push("\t * earns. */");
	lines.push("\treadonly legitimacy: number;");
	lines.push('\t/** The string the game displays, e.g. "the Great". */');
	lines.push("\treadonly name: string;");
	lines.push("}");
	lines.push("");
	lines.push("// Every cognomen the game can give a ruler, keyed by zType and");
	lines.push("// written in ascending legitimacy — the order the game awards");
	lines.push('// them in, e.g. COGNOMEN_GREAT → "the Great" at 100.');
	lines.push(
		`export const COGNOMENS: Readonly<Record<string, CognomenInfo>> = ${JSON.stringify(table)};`,
	);
	lines.push("");

	const config = await resolveConfig(OUTPUT_TS);
	const formatted = await prettierFormat(lines.join("\n"), {
		...config,
		parser: "typescript",
		filepath: OUTPUT_TS,
	});
	await mkdir(dirname(OUTPUT_TS), { recursive: true });
	if (existsSync(OUTPUT_TS)) {
		const existing = await readFile(OUTPUT_TS, "utf-8");
		if (existing === formatted) {
			console.log("bake-cognomens: no changes");
			return;
		}
	}
	await writeFile(OUTPUT_TS, formatted);
	console.log(
		`bake-cognomens: ${all.length} cognomens → ${OUTPUT_TS.replace(REPO_ROOT + "/", "")}`,
	);
}

await main();
