// Bake the family-opinion bands and what each one does to a city's upkeep,
// so the Economy tab's upkeep view can say why the bill is what it is.
//
// A family's opinion of its player falls into one of six bands, and the band
// applies an EffectCity to every city that family holds. Five of the six carry
// a YIELD_MAINTENANCE modifier — a furious family costs half as much again to
// keep, a friendly one a fifth less — which is the single largest per-family
// lever on upkeep that the save lets us name.
//
// SOURCES (local-only, via the Reference/ symlink resolved by paths.ts):
//   Reference/XML/Infos/opinionFamily.xml — <Entry> with <zType>, <iThreshold>
//     (the band's inclusive upper bound; the top band omits it) and the
//     <EffectCity> it applies.
//   Reference/XML/Infos/effectCity.xml    — that effect's <aiYieldModifier>
//     entry for YIELD_MAINTENANCE, as a percentage.
//
// Bands are emitted in ascending threshold order, which is also the order the
// game resolves them in: the first band whose threshold the opinion does not
// exceed wins, and anything above them all is the last.
//
// OUTPUT: src/lib/generated/family-opinion.ts (checked in, self-contained —
// no .bake sidecar, so bake:finalize never wipes it when this hasn't run).
//
// Run: npm run bake:family-opinion

import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { XMLParser } from "fast-xml-parser";
import { format as prettierFormat, resolveConfig } from "prettier";

import { resolveReferenceXml } from "./lib/paths.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUTPUT_TS = resolve(REPO_ROOT, "src/lib/generated/family-opinion.ts");

const MAINTENANCE = "YIELD_MAINTENANCE";

interface Pair {
	zIndex?: string;
	iValue?: string;
}

interface Entry {
	zType?: string;
	iThreshold?: string;
	EffectCity?: string;
	aiYieldModifier?: { Pair?: Pair | Pair[] };
}

const parser = new XMLParser({
	ignoreAttributes: true,
	parseTagValue: false,
	ignoreDeclaration: true,
	ignorePiTags: true,
});

async function loadEntries(path: string): Promise<Entry[]> {
	const xml = await readFile(path, "utf-8");
	const parsed = parser.parse(xml) as { Root?: { Entry?: Entry | Entry[] } };
	const entry = parsed.Root?.Entry;
	if (entry == null) return [];
	return Array.isArray(entry) ? entry : [entry];
}

function pairs(block?: { Pair?: Pair | Pair[] }): Pair[] {
	const p = block?.Pair;
	if (p == null) return [];
	return Array.isArray(p) ? p : [p];
}

async function main(): Promise<void> {
	const infosDir = resolve(resolveReferenceXml(), "Infos");
	const [bands, effects] = await Promise.all([
		loadEntries(resolve(infosDir, "opinionFamily.xml")),
		loadEntries(resolve(infosDir, "effectCity.xml")),
	]);

	const effectByType = new Map(effects.map((e) => [e.zType, e]));

	const rows = bands
		.filter((b) => b.zType != null && b.zType !== "")
		.map((b) => {
			const effect = b.EffectCity != null ? effectByType.get(b.EffectCity) : undefined;
			const modifier = pairs(effect?.aiYieldModifier)
				.filter((p) => p.zIndex === MAINTENANCE)
				.reduce((total, p) => total + Number(p.iValue ?? 0), 0);
			return {
				type: b.zType as string,
				// The top band has no threshold — everything above the one below it.
				threshold: b.iThreshold != null ? Number(b.iThreshold) : null,
				maintenanceModifier: modifier,
			};
		});

	if (rows.length === 0) {
		throw new Error(
			"bake-family-opinion: opinionFamily.xml produced no bands — did the XML change?",
		);
	}
	if (rows.filter((r) => r.threshold == null).length !== 1) {
		throw new Error(
			"bake-family-opinion: expected exactly one open-ended band (the friendliest); " +
				"the resolution order below depends on it.",
		);
	}

	const lines: string[] = [];
	lines.push("// AUTO-GENERATED by scripts/bake-family-opinion.ts. Do not edit.");
	lines.push("// Run `npm run bake:family-opinion` to refresh.");
	lines.push("");
	lines.push("export interface FamilyOpinionBand {");
	lines.push("\t/** OPINIONFAMILY_* zType. */");
	lines.push("\treadonly type: string;");
	lines.push(
		"\t/** Inclusive upper bound on opinion; null on the top band, which is open-ended. */",
	);
	lines.push("\treadonly threshold: number | null;");
	lines.push(
		"\t/** Percent applied to upkeep in every city this family holds. */",
	);
	lines.push("\treadonly maintenanceModifier: number;");
	lines.push("}");
	lines.push("");
	lines.push("// Ascending, which is also resolution order: the first band whose");
	lines.push("// threshold the opinion does not exceed wins, and anything above them");
	lines.push("// all is the last.");
	lines.push(
		"export const FAMILY_OPINION_BANDS: readonly FamilyOpinionBand[] = [",
	);
	for (const row of rows) {
		lines.push(`\t${JSON.stringify(row)},`);
	}
	lines.push("];");
	lines.push("");

	const config = await resolveConfig(OUTPUT_TS);
	const formatted = await prettierFormat(lines.join("\n"), {
		...config,
		parser: "typescript",
		filepath: OUTPUT_TS,
	});
	await mkdir(dirname(OUTPUT_TS), { recursive: true });
	if (existsSync(OUTPUT_TS)) {
		const existing = await readFile(OUTPUT_TS, "utf-8");
		if (existing === formatted) {
			console.log("bake-family-opinion: no changes");
			return;
		}
	}
	await writeFile(OUTPUT_TS, formatted);
	console.log(
		`bake-family-opinion: ${rows.length} bands (${rows.filter((r) => r.maintenanceModifier !== 0).length} move upkeep) → ${OUTPUT_TS.replace(REPO_ROOT + "/", "")}`,
	);
}

await main();
