// The one intentional delta between the frontend momentum scorer and its
// Worker mirror, expressed as a pure transform: scripts/bake-momentum.ts
// writes the mirror through it, and cloud/src/momentum-mirror.test.ts re-runs
// it to assert the on-disk file is exactly what the transform produces — the
// same guarantee the generated weights table already has.
//
// Deliberately import-free: the test runs under the worker tsconfig, which
// ships no Node types.

const FRONT_IMPORT = `} from "../generated/momentum";`;

const MIRROR_HEADER = [
	"// AUTO-GENERATED by scripts/bake-momentum.ts — do not edit.",
	"// THIS IS THE MIRROR — the source of truth is",
	"// src/lib/game-detail/momentum.ts; edit that file and run",
	"// `npm run bake:momentum -- --mirror-only` (no corpus needed).",
	"",
	"",
].join("\n");

export function mirrorMomentumSource(front: string): string {
	if (!front.includes(FRONT_IMPORT)) {
		throw new Error(
			"momentum-mirror: the frontend scorer no longer imports ../generated/momentum — update this transform to match",
		);
	}
	return (
		MIRROR_HEADER + front.replace(FRONT_IMPORT, `} from "./generated/momentum";`)
	);
}
