// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventLog = { log_id: number, log_type: string, turn: number,
/**
 * xml_ids of every player that logged this event (Player.xmlId) — the owner
 * set of the dedup group this row stands for. Joins to
 * `game_details.players[].player_id` and `player_goals[].player_xml_id`. The
 * key for attributing a row to a player: `player_name` is null as soon as a
 * group holds more than one row, and empty for every player in single-player
 * saves, so a name join hands each of them every realm's rows. Never empty —
 * every log comes off a `Player` node — so a game-wide occurrence carries the
 * whole roster rather than nothing. Optional: absent on blobs parsed before
 * PARSER_VERSION 2.14.0, which have only the name to go on.
 */
player_xml_ids?: number[], player_name: string | null, description: string | null, };
