// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoryEvent = { event_id: number, event_type: string,
/**
 * xml_id of the player whose log this row came from (Player.xmlId). Joins to
 * `game_details.players[].player_id` and `player_goals[].player_xml_id`. The
 * key for attributing an event to a player: `player_name` is empty for every
 * player in single-player saves, so a name join hands each of them every
 * realm's events. Optional: absent on blobs parsed before PARSER_VERSION
 * 2.14.0, which have only the name to go on.
 */
player_xml_id?: number, player_name: string, occurred_turn: number, primary_character_name: string | null, city_name: string | null, };
