// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type YieldDataPoint = { turn: number, 
/**
 * Per-turn production rate (from yield_history, divided by 10)
 */
rate: number | null, 
/**
 * Cumulative total, divided by 10 — the game's lifetime total for the
 * yield (yield_total_history) or a running sum of `rate`, per
 * `YieldHistory.cumulative_is_game_total`. Null only on blobs parsed
 * before PARSER_VERSION 2.18.0, which emitted null for the turns before a
 * total series' first row.
 */
cumulative: number | null, };
