// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YieldDataPoint } from "./YieldDataPoint";

export type YieldHistory = { player_id: number, player_name: string, nation: string | null, yield_type: string, 
/**
 * Which quantity this series' `cumulative` holds: the game's own lifetime
 * total for the yield (`true`), or our running sum of the per-turn rate
 * (`false`). Decided from the save and the yield, never from the series'
 * own rows — see `totalsAreComplete` in
 * `src/lib/parser/derive/yield-history.ts`. Optional: absent on blobs
 * parsed before PARSER_VERSION 2.18.0, where the two are mixed and
 * indistinguishable.
 */
cumulative_is_game_total?: boolean, data: Array<YieldDataPoint>, };
